apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.*
    helm:
      values: |
        # Send to Loki
        config:
          clients:
            - url: http://monitoring-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

          snippets:
            pipelineStages:
              - cri: {}

        # 🔥 THIS is the important part:
        # Override the chart's default scrape configs with ONLY this job.
        scrapeConfigs:
          - job_name: plane-api-and-web-only
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - plane

            relabel_configs:
              # Keep ONLY api + web (your label "app.name" becomes __meta_kubernetes_pod_label_app_name)
              - action: keep
                source_labels: [__meta_kubernetes_pod_label_app_name]
                regex: plane-plane-api|plane-plane-web

              # Set path to container logs
              - action: replace
                source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                separator: /
                target_label: __path__
                replacement: /var/log/pods/*$1/*.log

        # Make sure nothing extra sneaks in
        extraScrapeConfigs: []

        # TEMP: print the loaded config so we can confirm it’s using ONLY our scrapeConfigs
        extraArgs:
          - -print-config-stderr
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

