apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.*
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc:3100/loki/api/v1/push

          snippets:
            pipelineStages:
              - cri: {}

            extraRelabelConfigs:
              - action: drop
                source_labels: ["__meta_kubernetes_namespace"]
                regex: "kube-system|kube-public|kube-node-lease|local-path-storage"

              - action: drop
                source_labels: ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                regex: "promtail"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

