apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://helm.plane.so
      chart: plane-ce
      targetRevision: "1.4.1"
      helm:
        values: |
          ingress:
            enabled: false
            appHost: "plane.kiril.shop"
            minioHost: ""
            ingressClass: ""

          env:
            cors_allowed_origins: "https://plane.kiril.shop"
            web_url: "https://plane.kiril.shop"

            EMAIL_ENABLED: "false"
            ENABLE_EMAIL_PASSWORD_LOGIN: "true"
            ENABLE_MAGIC_LINK_LOGIN: "false"
            ENABLE_EMAIL_VERIFICATION: "false"

          postgres:
            storageClass: local-path
          redis:
            storageClass: local-path
          minio:
            storageClass: local-path

    - repoURL: https://github.com/KirilMilosevski/Enterprise-k8s-platform.git
      targetRevision: main
      path: plane-overrides

  destination:
    server: https://kubernetes.default.svc
    namespace: plane

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true

  ignoreDifferences:
    - group: batch
      kind: Job
      jqPathExpressions:
        - .spec.template
        - .spec.template.metadata.labels
