---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgA4B5Wg643gc4aWxGYp16geWZQPCaEyV+Fl85Ha4TYQi58I8DtFta9aL/W3EeL96jBwSF3Gt2V8lPu8GSzo2WqOGKf2QX0OtaV6OhAzzNt4OzlZihCrXm6b83LOFltxaWpMJIEaP7aW+wYHMqN945Ilh24BwHlu+cpfF14NRrT96bRPIWb7F1cJUda80FaFPAOnOua0u3NknKjxAmsFOqAwoqdZ6uYZAlTF6EwLvHgamPU8RFGp+4fWiTuhUzPPyzFdVRHx376+J+on6/JCPElKck0G+C8uFzlQgSUMEXAU/qhy7yOtuoUY8ecZVE5Db7qhPuwfE8dW7oVprICqDYU5qnPTQQvzPWDAXOqfzejnz0aG4auF1dJASNCjv0guiV/UHmlKYVIG/UgB43AZg7AdbSEJ8pqPHmfmTBejZfBokF8gQp8awoe53awe8H7LzUFaa0b78HYtbGU9tcwlcERHkb5UFEMAEXeP4of3H37/qt5lDAzhGM/22pAyibBcGhA1Unl0ShKlQETmf/pEgmOFO4wR2cQeOcIT7udfXOeNS48LqmMauVbvbKo4XjQHg9fb17BFFXCKvPGvt0T/72TPCOl0nVblbP/+25gIgRkbsnJYAklUukfDNKGsciLYBovO3Yzc2CREu5bxc5KUXC60i/yHISviag8Q6r/csv5F8gXDTKFtecd/STcMhIRJQEK12I/LaVwd2qP4vHzWSrDNNf6B3iIHvm9I65OEDLl6123Y6GN/4lsb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare
