apiVersion: v1
data:
  TUNNEL_TOKEN: ZXlKaElqb2lNREEyWkRZek0yUTNPR1kwTWpGbU0yUm1abUk0WldJMFl6ZzNPV0UwTkRVaUxDSjBJam9pTVRRNE1UYzJNMkV0T0Rrek9DMDBZbU5qTFdFME9HSXRPRGhrT1RBNE1tWXpOR05oSWl3aWN5STZJbGxxYkd4WlZFVjNUMFJOZEU1cVJURlpVekF3V1cxVmVreFVhR3BPVkdOMFRqSlNhRnBxUlhoYVIwVjZUMVJCTXlKOQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
