---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAPszrnNySIyaD8Zx6RjtPcUyWD11WNwN1gKJVKGxJ29amGWMjURtYa7n94ULm/L8j4W5i0DIULs4xKC9UHBiIVPAmmCbmjE2gCi+d6tyBtFwHIv84XCyl95uQJhtrnNOUjajPXQMSDUaVm1FM5f2LcyNv5Zs/BjmVbx/go8B60FQKWhGQpcoDpisqadXvw1nWiWspk8NzqiWoBsBhCLBKrRIBYRIW8MaOvX4d1N4KZTNclF5dLMaEbVn4zNVMxzJp2tFoQV3s7da8FHjyXRpFu6XaiVLRu3osMludLlseRjNe9P2REjRss9Jfp+rgF3dwfbxUR/0opTobut1OEoRE5rwzR/lrpK5JWKZJRVk0cDOxb5zR8XS+9aeUTu9g3qOmp8PVVb4EqSV2dAGPECUGvq09Q3lhcLTtTtFZ2DhZIPFykgGbuDzd/s2VjLD/rlQDt/kLmgvZb5DqdmHFj4pvuwl/my+g+dxiCDyDeO6NKyeX4Uc93jV1xRaUhysmworF3EppequeZw+SMf22a+/fXHtPwOXgvXDCm/RE7ek0XsY0KOCAyX97aO7Yk0LOdsNny5MLyGQcp61rRn95bHKQpF1xYJjuKuq4cFP8us+MiQns+3wnwws9P3B3iziJrT6pSXbz0LstButrlUI+mYFdbONgKPoXSwWin4OHbgrgXoRU2dwrjFIU8DKQ9pGVeR09gOE5bGOZInkKULcuS0n1OyYs3qlhDou/acoIjyJ/o4JnkCFIzK/nbvRuHcm8KaVJTDoo1YCxOKa0/5Rk+Rne26LP/ASprvvQaRVd8fhi49C1zfxDDohdjpA9p6hOKNjRdF6u+wuMMtkQ5O6sLnFeK8bXYkbrhU1fqj1r06ChnArtH/yXKQGsZ5+Aj0pR0YhC9CUqMZTZrVGJ7T6IsX9VvXHhDJpe+ygSm6Sr51EM5y1+zFSUDTmgB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare
