---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB5X68n/wmBirkeCJKkbXhwLqFpVv02pZSLem4506jyOJCRdoQWwAeEhda2G63k//u22o+oZ6zT/De1veAulxacmhu9AtBbYUxTADN9qCk7D3AGAGVQRUwVt3/HWzmOpCCVj32wZf63Jlgs4kIFJ0PriUZxcBt+ksJr5HfOQ3f2384/hVs3ubkRLEK+vyxUKh7JcDxq1Q3tzbGKBcNLNZSHf5DimLSaAXiYSXToxsRe5xbaIqtCveloYTfWCUwjC/a0G2eqpmnamO75DxC5bzA+7qo4f+IExRIGThjfFsMmngTxyJqt0jEZ2RXnqJhO8LUxYrl0RaUrtg0Z5p+tJ9hC283masrvS/cAHSjkagHJLCjb/QkKWu4vt/28+GARZSjqfb4PHiCWhdCwilQXU5bLFV6DYhFDcOyFOTVlCUAFK6jrFXfBuD68R6Y/di66dlVjcDapQopFQhR3kt1ADmPfN3cWcpThWiYTFBtAvTqiUP/pcaUMCvmUzBCnfLb351Wv+d0xKQq7GtxwZML4sT5FRI4IMhFGPobEY2+RvTWBZL6nz3yqeABhP2ttLaLoGXB+dOMNC7oowyUbbaaf3jSiwARd4t2FDD3QswfC8kRFuNRzTJw1CT4WveijCRagoznHsvA+nvtL60S84aIL3t1jtwgM8sOhx1EK8rjVGoUMmnKBEg0Y2ZWilPlqzMqi2bw0keI/7gcd7fl2Zm/2nlFo23XnOnKJtWNqV/Qj/P9ENp2klEmveD1JGK64v+hGR9ded87RlzT/qLw1ztjNw9bPLSU9h3ZMT5qse3am5Ksu9ktWv5XlmVppa8pgx5mAcMdplL9Vg2effRg8kJQM3NUuhoTVoAFtdZ3WZDEB9WRmMxzloB/vZRSy7UDeONYNZb/Hpvv0dDOMosQs4T61kDqlHTX7wYg4EpzMCU3kMuSX+d/pMJjw73WG
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare
