---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAexnMcDRjT7QzphfELX1wsM89T9S849KNREWNwHlIVsOOO0AdEkrHeHfHdzj6m+CMFfdXdkmfCps0m8C6zwYEKmPaqzZXKFem6fzdGL013Yr5W0CEtXvZSl5JCXnq0P9Ix3MpAzCdlqC3NFAaS1ow4CY0yOsqw4a6VSknWLH/WBxuCeT9LVCeYJMLhxuQVEalnLi1nvWCcYJMg4CTbZGmYgBGEJoaDBIKXZcmgL6F1rAGUGcyyFhy/u43yvOQb1+mBLoCDABfAU7hB5WDwbM32znFJv97B2WVLAxD2Gcg/SC4o5ah3M/ZJbrtWBucHHMoQXVhZ0O+KdGzxlKbehJI6A+jCB13T3rmA6zoLYB03B7M94ABtZ/IMwNj+IDtJC78cItK+6nRkvAZowCBfdt/N2hrVAqGmAaxVmN6A2nlZczpvnFlYc7Kl4dDZYwD3ORz9YOkeF/GWZEgigAePV3Y92BADariKM7hx+ZpKoemOumxJv4XMdUMO1/g8oG9ltf3JTdCTh+QhAUdbOBbkLtN2147RkvCZ+rClFlmedOmLXSnqDn3JK6RYGk7F53rRvwjAeDx1xNlL14Ps12dPsVJPRCfffV8OCNZ54vsKTBttJk7A6BNn6Ilv0fKBKcDBadfUGJqtuW/ETIz3C4k82ggsbE40SWuQLBZvXpduaM0w/viCuV3XtUMKV5D1KdA+JBtELemw8zAtoks5s3pkCF/xBiIFPOUlWK3WkKnAEy37WGmgkyFeWPoaCq5z2bQrZ0LVrUBozWmycJkjrDKncETpQTUcri+IfIfAkzxf+EmUcv89/I7oLODunFdAUiQL3XtOJtPWDC3SH9ZPDdZL36hQLX/lSOU5jg+r2fhS8PHsan32K47M42pkXvfbacq9bvg2v6SjzYzo6dAgXA+nGtv1EMNHvbRP9pKDvibJA/hDNVjJX7ylTdya
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
