---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB0FVSFBJOeDvRVZDEcwuL0RYCujb3Kna0wo9wuxMTd3G+cazYGS6EEBc5ndnw2rO9lleyxgCJIabg6CP569hT26MtbyE4ZvlElOBj5duQf4ADnRvzR5vcOcDaj9MTPHDe37wJRJyxQQs9tfrBNL8u3pLbTvaKNs7L4n9gqcJ+RRvYJkFBsZuULq0YmgJ1rv6kJalNQh9GSTa9G/IRvnZNx41FNiHtgWFNR07rKef43WqMQDES4BwsZNLm5ryFj8PwfWd6aKiAayck+xQLFIuznKbI2epOexq/rDj+MpQO4X/eDSBbvTbifDuQ89Avwjthw1KOa1uO7IH9cEGYY+oO5pSbNISWxbI1AIjJ7Evc6d5NCV4UUPz6vvV2++/ob8rUNgIHO2MgSzNHzswEc20AQsnyJuEA5FEkNVEb2vOcx3C2ZFLNzj2SrXPLM3pxq1H+/6oiDjOPXWpVIumSuMqlTfSzhmYFGKt5cvB4hoNRP5FcpVTT8AGeen+gqkb95ClHbbZ6wH2Q2jyOBgKe6Upz7BZ/gjemysJBQ/jvGdDtX4Vm7DtV8GoeH7jVXOpLAGtEPRlqJCBGzQIbrRh3Ay3Bz5lBPig829Lkc6Oy8htp1+NSYVxvkzRlL1XpzXentDAswzJswik+MKUpEI5VWw8uJLLx+2ajZxvuJsLdN7g0MuVbSVI3SRw/frVIKXza/2KPRV94lyTtJeJJQyPruu3+X+DOmeXDBNx75A0LGQ0cEDQ9wt4bDVHyVOoe1YHZg0vWs1FcPcKXHVJ920yjhLab5WH/+fpbu2TNly9lZW/LKCefx2R9mhrF2iCZjuz4L32ImSJTrl2VQWAdhvd/7aJnAO3daAUJfJRNRRhKZirBorY5YH6bTRcmAz/B3mBZBVGfDK6kMpldDRJD/vqKe7Nq0ejBXQ+GFumSmiDFZrWEO3QZCM+8Gfqmm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
