---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB0ox98yqaJLIYAYAZV6tmnbKHUioZhUW1ZOuAeaisCd/9G4sZMqp7vLM18h2D8nyz7dusSHK++q4TiPpLkJg1LH4hyBHaMWDZJYKku8sA4HAdkBwXlEP1ol2SwvDZSAXKpWP3d43ZFgHmv+IhzXGL4mbWB8++HSXCqP+1a43Ae0J/rljNteHTLN0lRBMwRsBz0T/8cqCWsDdYV6JNtzu1PvJdHVepmBh8j6987UmsAUyiJViYYPs16g1b9gmI1aGvN7KhuG/EahnkpRUbhHLp6fqVe5M6sA6UCK0WGk3+gCDssJcjPrrbqdswxKbucMPz29DIodiePUcRfebFGwdxOA6d5OzS6DJ3CcwAlv543i9prcPMC1UZdiLcASS14Qgq82cBoIpU1tyaJfJthJlrplbikVHUbOU7qg20upzN62G4A5OHPx39YFGZT7Nnied+lbiQEe60UaUanHLM4QpcZXdmfPSL6CDujF7AK6sYDzOpngy0g4JprAbSdP0/cXljwfrEvU798Ue+kMpGzf8nAPIwGAbFXiby+6MjvwedYerMfb3P6WHzV02+G/jJeurTazVCB6M6vk6PlTy6/mYge3BS/ptFa9JYzxo6AfMIIOnbKz6QlCyPZu/4C7lVI1oaSsHw+jmGYGB39Dxfzk7hU6zidmJT1/DZYSikB4oQX/6lk4m1ausqUcZjh0sCTqNjsneRteFMzpljVKqMhnfB+iU4kzb6eO18mogCHMCoSuY6ByZL668nehnBs+b2cywnLpGOXNsjhQKRJ8J/6qoDgBdDlHuB5PR2W2qpOb+CyWydFhKS6GZRcpZoH4Bg/P/eo5UB9SskP4lweDdlTtww/v78EWrIGmpv9wDxJr7C/TPjE5wyJTFMGx/k6pRz+/7bjMbgz5fNHM6pCmSfm2EErxH1MXuizYPEnHgoBlkZ/JgxHZncPUuN7
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
