---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBaEX7mOb94/RSqbaGtAjQtnKRaVFtOo8S/ZszQt3Y6rhY5vcmP7Y6iOHdy/C1g2D3GyJBxGkaPa2tfiSYIjZao2rvFUPWUgUyfPGiAPRtp37GJv8JhL/zf2gOz2/r2kGHYigOcATuSbBnfpLLHFbWXbC/sbxfiE6E8Jd/rfd1rUTJLhizD+mjRTV5y5SihWdV7v7EEt86xYjdQA39H49qNZl5Uz8tMm4XqRUysStCCtCfKdx4xkzHArco+hRjEOlpyP+mLE8pBAW3+rN62u5nroZAUGVyN2OME8D/pQBV93EXszSVrioUfJAs26pvjf91qxxj2vVCaCWdDAFBAG8rMiRmyRarGt1JsvuQmLLkEHGquvoQ30q0KIU7KlyYlLGblGcyfxc1ZaSl0b5RrNyQtfORau6G7x1nzSLdqUezOfj4rwLtY5vuSg0Kk0qlJ891ebvsX1FyGimqxAVYC0i9hacBuj4YOOdXVTsEm1uPJWTdWdE8lzPisSG+ulBVBYRO2j4IX+ciDe9KsaDCLKqE0puTcAkQdiCDGi9y1EOl0XEVNgaW6xfTHv9H5PsLgjcHroWHQZ1KlkgSFWkoAuRGL3LTEpXDMeHjni3fWUut5e7tG9LzCDBBVgIqg9tvMsuFS5kNWFyF7eWx4X7QvScPoGl6YUMYIj6cBhGjWBYWCttsyIJwpmNBYg02hnaA4boh6cs/RSxl8o03ECRCkAbiViOFi+bi8JxgOeAUu84VOpkFxNSvRZtYajiUqPeYcAHbCzzbgvVI1cgqxRdnEM9qQY/d8bFk1AAfajcvYXr+7EcuSOJaUKvObi/w19hnOei9/ieybpMGSgO2Qo0vNuueAtWaZL6i2Bb+Wxun/50TXEfkiNwG3edGEYFSCinHp7dkEF7QCKE3zFI2YAoFFNrFlAIidV2V9w+9op97UswC11RMLdylK2shi
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare
