---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAoRhUfaidMDLWryRvdP1WIJBKOsxzVHItR72sbIBgxsnt2HifN7sqR9lEZKqZuZGajdyQfFsqYYFKfUzqoOUg5mgWeDvnP9gxfDjFoLwlOkpcbGBgMYn2EwRU3oRsxwTqs9ZtV8qJdqNx4/0/nxV42ZFG3bmQIt8GOnLKXMhRyCBN7FRJ1H/Age380v8VEQS3sgiFHTHcyvYorI8u3MNZB1WuXkfInldzqleEjX0ovgSrcK0aLMuUERHamPIk+c0Ba64Liy+6IDI+Kz3ic6CRlPCix0vHHJrF3uewZqiGyw6BVibWN0nBJwje+yG/jQXaFPf1iucWc+KlA9Oc8mJ8S7TCC/8ZpMAgQ+8na80e9xgPPwQmi16/mXXHxxMuwE7FvieVYjDYiIWwX/JF7fQmaCxE59X3afpQcfFPY3wPQVaYKvNT1LHbqP5Z0tv1uDQU1TdlUXDJDZqVeWr7NQAdSY18C6FzOATEJMEzevKaJgBK0pXX3Fo4HidSDSYEYGx4qD7RbPC3pSsZo0oXwDdZGUBsGaJV82w7VzxbWP6NnG8mYr4ml4FaLJK954PcHuRtnW3bhA1UrN/pLt3d+s1uKi18ru2fOe5atSxyJ/HLNp+ozLA4AQru2wOWj36ooxtKmVfDW49aaQdbNG+eNVaxd2U+3vET46qRuoeHsHYxkP9wBkv5SbgNBC4uQTmPzVuLsmIZVg7heRqaVsqyb74ND/r8Fr3EdnmZuv5Jj6ntnaS6NAfsVvOqGBtuL83TL4+w+2y//2NkHlD0b0ARGMT3rCTQBistZrzoYk1hxRbUF1ExpGtx+1Q7hm33VObb4J/6I7f0GJzYuSMhWQWxbSgFdMHxC3ekLq+PFVhiorFB1qc4BEL86tDAKns8nwglWU5RE2119dIX8zOBDAsbvUmQi9vdH7z1BWQ2vnhcGwEoFtow4EnyA00gf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare
