---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQfzA539ltrLXX5dBZisXCXcYyVHccDF6SssJDhyaA0FSw7U+n/VRua0b9FLbTTpA+j8EflAToGEq2/KiLBQy0STLM5ogD99xhBtAZup4Azl9AxPh3IgkGn6yeC4Fp7y6uIXfw7uA2hNvV2x9Z4EMoE4yv90jxONIJStOFsrEsc1U10ZN/LJS807fvD2Ild1AQ/gUvJbjc+ABst5aSEUde1k4Z29uRTVG69NrQmKvyT6RunolGs76KgFky/XbTYqhxRghfNypWfhNcQ7XQDe89Sww0zoGYoYGvV3WW8i6m7mgFhvyoryTxIBcwhbPZAAGFU0jEf+1mDQ84jJahJzjyxfcrcO5VEVbMWk5d7dbmN5Xx1PGZ3tzb1TdT9M71LnClopggKCX4zZF00UXuApKNLD6jZLqk43CQXHmy8RHQLW+cwU2Qd4hy4W1uzUoeEuZ8xm6LacKchcSHcOBptCGjubDJ8R3DOtkYv/gOMxR+9veDBxQ6jaCWnJPWdeUhGCxTpFyZ64FLTTbdaTe5UnWPZJHCHTYb4laIEBXTnA/eHAjfqUJQ1tXN1MOXeizV/quLxVOWgbpp7JOPC21kjGpANC3YWhNh553gT8ayGdx1uEoSwnN9jle+iziZi4702NKl+/n17uNtscauZBEG1+PUW7uLCyCSIx8cDQQSazprMPeTDUjUdVYF/dJ4V7e7sccvqq3Vbg==
    admin-user: AgCQZ2r0f6tNKsxfwq1M0RkqkYLvkgQltTbps08yxwoBhKkPQElnDksQpC6jkXSYR7FRAYrz9Sgve1gh8jBt5+Lgb4JOe6dqSTarcI58xI8DAQsXI9lryWybHgcsEW5/jz0w4cWH2RCCKyK30hn0zvIrRXAyEy1Iql81P+d7CN/D51I+HHX5roMqS26IB03fVTgWC6GlKI0Tu8jRkbl8LPZpR/fNkGteqSBgwCcQGA8x84hkgierHuk+ltSbF++LFiSOODU53e7HIms0C6rj50PQbUhQPUE4quBqHI6oCuEsX42cFGF+SSWsz99XWnaVHv9A+5fzuwZC0VNNaiAB/4xEtXfzjSCXSdjAu+qgfsUrN56c5pgkEHZxbepaKhAYBnz/RfiJhpd0ngF7ZAfAOq3JY/sP+leELhk7jeHAwrkS57/ky3iJuAasdIeZUDo1fFwPV9I5e8G3r1xq4Da6adD0EvLL9u7nBdQRD0JH15iXPKXWxOOLcwyWL8dHSkyKF9yVzSRMbFP6uTnpYyvK7qo6KAAM8JW6j8L+YhaYN8FlpzbselD1FTF6r1+L2PEKpGWU/vha6JxgtCBFuovNNIOVpF3IVnT9DkVU3blUSLDlQb4rh/BZHqcEJh0zvgYORfsBUMPhO3/UN4qJksLBIsUwTuLoIQkL9xc9GvuJZnymS08NLdG8qIsS5JOnWsqEyMebM13R0g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
