---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAoLP/xpCxpzbtSsCU8mhC3M3cXvN5Tqatt9WlKQaVTlIUO/UBX+p6S9BD2vWisNGR/5kFi8z8ETC/v5XCnneCWRQDaJD+MCvOEHNTukrfIf3oCXzYAEBqJvint4e7qT0z9U06gRVGjOvrA0Q2Z8udMYcpcJWDTLQOetYEkwPRj7QqOXNxPme3xIHIsTJxensKlWD0YD+O+X7Uimos0Ir5SETalfYvmimwsPIhyzZiVXSmmfSuiBUXOCkg84d/bzC4umARr+h1tWEvRzIY42rQyTERzMRWhCvoQsW2atgsMUeKZsr5UdLX6pGwwFTrgBew19tG/mll26XwRj+8Bi0txs7Yl1GF4mY7DaBKZ9A2oJN7NpSEOHG7s0vCe8rhOODS9y5ETb2dTvdiB4MCT3QCk0ClKtR2IYqdF5/zas1zg8e/8xMEf4skm3UXHF3HQ86xKVwyojJwDJxmTCsC/eTu2mmRfyvZ9OmkIPjxlz6+zWFeTqnqompz2Ox4zNXkLd36f0lpjgsz7OVAiF633OtPwwKLF8VoJF71jB5+SqZt5KR7YLrPcxwIwpl6DPBAHHaxFP4b5VfGOJXb6psta44vidi+ygVUUNcno0047dyhx9ykiTJQznCF7W2bN2fNc+FVVffT2pHwxHeCwyShtvq3GuXEyu8WajtGRaztxIOVXfLKbdixmQAefal72lt3OOVdXzmMghQ==
    admin-user: AgB1v3Xm536MTM8vJT4Jh4F5gon+pw/BGl3l/GAbS87Mr/qCWPcEwtfGruYEfWV7gNseVvygh+M2vreWVimZa0O4QBTP1gNo+5q9aq3DWtk6EYK0YdX2AbX9CTNoc+rXcw77inVyW0Q1N7T/ywKG/sdcR9DrpphkcjhwkX+LsmgQzXP0dl3CwnVXu6jPHQbMmYoX4SySiaeTvE4r0HbZQfN5MEG0+3sHRS5ZPQ7mApFf9i6CXRGDp6YVy7elLu3fIYkT9iXxpFbnk5t2b7WiSMzvkx6TmuzP6a9v8IF2ek20xoyB6htCwi9oRFISUmLSPcB9KlxfwRVMFMKu+XR0/VRrXXmRaraStlsm1o4PCHIWutllBUJUKemRQd5/5O/VI7Q+Z7PeMCFXdW+lYIpj9UVpVAOWTCRO456wN01lRFQfLLVegB+wJ+qI/0k8EgseViu30FnGMIcnbcRAU0wsiUGXB2qeGHBtZS7KU/PWJQFGHCVovgQFihTdA154MTHoKz/dXr98dFFV5XiSAN9E9d6lzXrftpWu0MqN0AaGi5kYrzSWLR85gMQwkklVlLHucnbQWMWRDiYGSgxdtE4mZlENi7DrC8CH7rhp2f/eIFIYJnlrPZgV2cU3h7skZuced1F07L8jhVBkILyEVPcUp98tcHtGxnq6CdhnbM42TPYiJ/l7GROeXoe61gS7+ggCJDhh5kUHHw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
