---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAx+XiqK0lEdOmSsnSeB/Us52WGkZZMEplvqGXRMVNImZ7zcshBK46FDhQlp/fLJAuOHKslxRUc9+1myezxyqgn6Ox1za2jC8XjZhHFit+E4g4iEBeRxRbU540UiEFRAkxUHQtNFtprY9jEdepOUNiLGck3gHfm+dPdFrDYNPJiJmwazTH+pVCptG9pjBFFFG0msHCfkbRv7s2ekampPk9ezSSat9DijItiOApVrAvF3bIbNpOOUr/sDM5rt17UoVfStacp7hwiWUUKAIOYN9KE1ffNX3mO8N2JuRCNAyQs/M/0J+ryFywEJeLrlrqCW2vlp70YjeqPVdUHeg+RTyWmvvv58sQMnB4pY83rjxIJLeQKOHRzkbAjN+jcholcD2LYt2/PLtHZmGiMCeBQ7f8QI0G2mrLzHMMbTG2q1e+qNPxoWDC1Lln/co1+opm1jiRLpvXfZA7TLo7Suiz12kag4XfLu9E5QVcvyQnvz4GHcH4HrzFILkblrLOAQGOrl6HUOUTQXSG09k1HoNlz20FMe+6Hc4iry1hK1Qe5xFd5nGKfCsMsz2cCkvpN2BFwq/ncQqqXZPyXtywWYKNjIZubbcSPHzfBBNXD+VJ5+FEpRjvcDLC3jei1d1R5dukjrHfdjrVMYVctx/DHEwbCiieR4yMrdWawuRWPf1QAh/DbKLhL7rumzEUerhE2ZKwGPXH2NgvuMQ==
    admin-user: AgBGy/QVbITKZ2IR0RoHWxL8l1DhvLqap4YbobPp50jbhRABNZnse+6D07EbDaYFQeKklNuvyPSJqTMXFDHLUSANhLrwcFzP6DmCr8m0qY4B+grxm8sT8zELeS53UX4VODryHZ5XpCnzgXQ4rB948JV5rZnFSCrjy0K6TIINQ3Za9UnrMS6SV7Oo/1+KydBZ7fhgPiraht6AWqnNCTaK9bkaJ7EfsNh9p2CCNOGH4UI5zHhtwyeERJRcmQekVXJAOI/u3MhH73Wxd5C6MiRMjCZVb/HQshee9ON/nfUmwm5UE4iSd5O5PQH2xd05nwGDBtGZSde+cu6u34q+AdoXlS/yLRzj+yURht8wmOjbm5VbgP/8yAGra+KGX4PSUMTwWBAMBvNMqvvEAbNx7xY0nC2tF5wN2P4okQtFF9ZKVc8/4bjp71ilywLhoj8V5y63qwLpFQ84Ow7rm3y0oqGmiPYam6nhlb+8q84c616Kg18eAelzYbF4REr3utmxChGfFtfHy0yNEIFuDN5VDiS5fh4xh1CbOquyYdfR69Iia3S1ZNOiZ1yiLJlClT4CFw4FpUecyJutty1kgAvwRUmbHkt3tIQ0/Xw29v+So3XqN2nMbjF0S+DS9PFfiOohdPv8JSFeGYEaxb9JTFyYBn5JYsD/867K/dzbL6f3KqlLQdgyrA+5VnGHSdFjReK1+DSvveAbcrrM7w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
